BEGIN TRANSACTION;
  ALTER TABLE
    tasks
  ADD COLUMN
    destroyed BOOLEAN NOT NULL DEFAULT FALSE;

  ALTER TABLE
    task_efforts
  ADD COLUMN
    destroyed BOOLEAN NOT NULL DEFAULT FALSE;
END TRANSACTION;
